name: Trigger Action on a CRON schedule

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
