name: Cron Test

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm it's working
        run: echo "Hello! This cron job ran at $(date -u)"
