name: Scheduled Branch Merges

on:
  schedule:
    - cron: '34 17 4 7 *' # July 4, 2025, 1:34 PM EDT (17:34 UTC)
    - cron: '9 22 5 7 *'  # July 5, 2025, 6:09 PM EDT (22:09 UTC)
    - cron: '17 20 6 7 *' # July 6, 2025, 4:17 PM EDT (20:17 UTC)

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          if [ "${{ github.event.schedule }}" == "34 17 4 7 *" ]; then
            git checkout feature/moving-average-csv
            git checkout main
            git merge --no-ff feature/moving-average-csv -m "Merged moving average and CSV storage features"
            git push origin main
          elif [ "${{ github.event.schedule }}" == "9 22 5 7 *" ]; then
            git checkout feature/visualization
            git checkout main
            git merge --no-ff feature/visualization -m "Merged visualization feature with Matplotlib"
            git push origin main
          elif [ "${{ github.event.schedule }}" == "17 20 6 7 *" ]; then
            git checkout feature/readme
            git checkout main
            git merge --no-ff feature/readme -m "Merged README and finalized documentation"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
