name: Scheduled Branch Merges with PRs

on:
  schedule:
    - cron: '09 22 3 7 *' # July 3, 2025, 6:10 PM EDT (test1)
    - cron: '55 22 3 7 *' # July 3, 2025, 6:55 PM EDT (test2)
    - cron: '34 17 4 7 *' # July 4, 2025, 1:34 PM EDT (feature/moving-average-csv)
    - cron: '9 22 5 7 *'  # July 5, 2025, 6:09 PM EDT (feature/visualization)
    - cron: '17 20 6 7 *' # July 6, 2025, 4:17 PM EDT (feature/readme)

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create and merge PR for'
        required: true
        default: 'test1'

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine branch to merge
        id: branch
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "BRANCH=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          else
            NOW=$(date -u +"%H:%M %d %m") # UTC time
            case "$NOW" in
              "22:09 03 07") echo "BRANCH=test1" >> $GITHUB_OUTPUT ;;
              "22:55 03 07") echo "BRANCH=test2" >> $GITHUB_OUTPUT ;;
              "17:34 04 07") echo "BRANCH=feature/moving-average-csv" >> $GITHUB_OUTPUT ;;
              "22:09 05 07") echo "BRANCH=feature/visualization" >> $GITHUB_OUTPUT ;;
              "20:17 06 07") echo "BRANCH=feature/readme" >> $GITHUB_OUTPUT ;;
              *) echo "No branch match found. Exiting."; exit 1 ;;
            esac
          fi

      - name: Create and merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="${{ steps.branch.outputs.BRANCH }}"
          echo "Working on branch: $BRANCH"
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh pr create --base main --head "$BRANCH" --title "Merge $BRANCH" --body "Automated PR for $BRANCH"
          gh pr merge --auto --merge "$BRANCH" -m "Merged $BRANCH automatically"
